site:
  title: Apache Cassandra Documentation
  start_page: cassandra::index.adoc
  url: http://localhost:8080

content:
  sources:
  - url: ../
    start_path: doc
    branches: HEAD

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

output:
  dir: ./build/site
